name: Build Godot 4.4.1 C# Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Godot 4.4.1 (Mono)
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_mono_linux_x86_64.zip
          unzip Godot_v4.4.1-stable_mono_linux_x86_64.zip
          mv Godot_v4.4.1-stable_mono_linux_x86_64/Godot_v4.4.1-stable_mono_linux.x86_64 ./godot
          cp -r Godot_v4.4.1-stable_mono_linux_x86_64/GodotSharp ./
          chmod +x ./godot

      - name: Restore .NET packages
        run: dotnet restore

      - name: Build Godot C# project (generate solution)
        run: |
          ./godot --headless --build-solutions --quit --path . --editor

      - name: Verify Godot C# build
        run: dotnet build